# Generated by Django 5.1.7 on 2025-03-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimentacaoestoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.produto'),
        ),
    ]
