# Generated by Django 5.1.7 on 2025-03-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_movimentacaoestoque_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nome_produto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
